spring:
  web:
    resources:
      static-locations: [] # use custom RouterConfig only
app:
  api: http://quaoar13:7100/gnd
  dontShowOnMainPage: 1012979-0, 118551655
  icons:
    CorporateBody: "bi bi-house-gear-fill"
    ConferenceOrEvent: "bi bi-chat-dots-fill"
    SubjectHeading: "bi bi-asterisk"
    Work: "bi bi-book-half"
    PlaceOrGeographicName: "bi bi-geo-fill"
    Person: "bi bi-person-fill"
    Family: "bi bi-people-fill"
  types:
    FictiveCorporateBody: CorporateBody
    OrganOfCorporateBody: CorporateBody
    ProjectOrProgram: CorporateBody
    Company: CorporateBody
    MusicalCorporateBody: CorporateBody
    ReligiousAdministrativeUnit: CorporateBody
    ReligiousCorporateBody: CorporateBody
    SeriesOfConferenceOrEvent: ConferenceOrEvent
    SubjectHeadingSensoStricto: SubjectHeading
    CharactersOrMorphemes: SubjectHeading
    EthnographicName: SubjectHeading
    FictiveTerm: SubjectHeading
    GroupOfPersons: SubjectHeading
    HistoricSingleEventOrEra: SubjectHeading
    Language: SubjectHeading
    MeansOfTransportWithIndividualName: SubjectHeading
    NomenclatureInBiologyOrChemistry: SubjectHeading
    ProductNameOrBrandName: SubjectHeading
    SoftwareProduct: SubjectHeading
    Manuscript: Work
    MusicalWork: Work
    ProvenanceCharacteristic: Work
    VersionOfAMusicalWork: Work
    Collection: Work
    CollectiveManuscript: Work
    Expression: Work
    FictivePlace: PlaceOrGeographicName
    MemberState: PlaceOrGeographicName
    NameOfSmallGeographicUnitLyingWithinAnotherGeographicUnit: PlaceOrGeographicName
    NaturalGeographicUnit: PlaceOrGeographicName
    ReligiousTerritory: PlaceOrGeographicName
    TerritorialCorporateBodyOrAdministrativeUnit: PlaceOrGeographicName
    AdministrativeUnit: PlaceOrGeographicName
    WayBorderOrLine: PlaceOrGeographicName
    BuildingOrMemorial: PlaceOrGeographicName
    Country: PlaceOrGeographicName
    ExtraterrestrialTerritory: PlaceOrGeographicName
    DifferentiatedPerson: Person
    UndifferentiatedPerson: Person
    CollectivePseudonym: Person
    Gods: Person
    LiteraryOrLegendaryCharacter: Person
    RoyalOrMemberOfARoyalHouse: Person
    Spirits: Person
  fieldOrder: type,
    gndIdentifier,
    definition,
    biographicalOrHistoricalInformation,
    realIdentity,
    pseudonym,
    abbreviatedNameForTheCorporateBody,
    firstAuthor,
    firstComposer,
    mediumOfPerformance,
    professionOrOccupation,
    professionOrOccupationAsLiteral,
    affiliation,
    affiliationAsLiteral,
    functionOrRole,
    functionOrRoleAsLiteral,
    homepage,
    academicDegree,
    titleOfNobility,
    titleOfNobilityAsLiteral,
    geographicAreaCode,
    gndSubjectCategory,
    topic,
    hierarchicalSuperiorOfTheCorporateBody,
    broaderTermPartitive,
    broaderTermInstantial,
    broaderTermGeneral,
    broaderTermGeneric,
    relatedTerm,
    dateOfConferenceOrEvent,
    placeOfConferenceOrEvent,
    placeOfBusiness,
    placeOfActivity,
    spatialAreaOfActivity,
    precedingPlaceOrGeographicName,
    succeedingPlaceOrGeographicName,
    gender,
    dateOfBirth,
    dateOfDeath,
    placeOfBirth,
    placeOfBirthAsLiteral,
    placeOfDeath,
    placeOfDeathAsLiteral,
    dateOfEstablishment,
    dateOfTermination,
    dateOfProduction,
    dateOfPublication
